export default {
  API_URL: 'http://localhost:5000/api',
  names: {
    first: [
      'Ada',
      'Adam',
      'Adelina',
      'Agnes',
      'Ailwin',
      'Alan',
      'Alard',
      'Albreda',
      'Aldith',
      'Aldred',
      'Aldusa',
      'Alexander',
      'Alice',
      'Alina',
      'Alured',
      'Amalric',
      'Amanda',
      'Amaury',
      'Amice',
      'Amiria',
      'Anabel',
      'Annora',
      'Anselm',
      'Arnald',
      'Asa',
      'Ascilia',
      'Aubrey',
      'Avelina',
      'Avice',
      'Avoca',
      'Baldric',
      'Baldwin',
      'Bartholomew',
      'Basilea',
      'Beatrice',
      'Bela',
      'Bennet',
      'Berta',
      'Bertram',
      'Blacwin',
      'Cecilia',
      'Celestria',
      'Christian(a)',
      'Clarice',
      'Colin',
      'Constance',
      'Constantine',
      'David',
      'Denise',
      'Edith',
      'Edwin',
      'Elena',
      'Elias',
      'Elizabeth',
      'Ellen',
      'Emma',
      'Engeram',
      'Ernald',
      'Estrilda',
      'Eustace',
      'Eva',
      'Fabian',
      'Felicia',
      'Fina',
      'Fordwin',
      'Forwin',
      'Fulk',
      'Gamel',
      'Geoffrey',
      'Gerard',
      'Gervase',
      'Gilbert',
      'Giles',
      'Gladwin',
      'Goda',
      'Godwin',
      'Golda',
      'Grecia',
      'Gundrea',
      'Gundred',
      'Gunnora',
      'Guy',
      'Hamo',
      'Hamond',
      'Harding',
      'Haunild',
      'Hawisa',
      'Helewise',
      'Helyas',
      'Henry',
      'Herlewin',
      'Hervey',
      'Hilda',
      'Hugh',
      'Ida',
      'Idonea',
      'Isabel',
      'Isolda',
      'James',
      'Joan(na)',
      'Jocelin',
      'John',
      'Jordan',
      'Julian(a)',
      'Katherine',
      'Lawrence',
      'Leofwin',
      'Leticia',
      'Liecia',
      'Linota',
      'Lora',
      'Lucia_Amabilia',
      'Luke',
      'Malota',
      'Margaret',
      'Margery',
      'Marsilia',
      'Martin',
      'Mary',
      'Masci',
      'Matilda',
      'Matthew',
      'Maurice',
      'Mazelina',
      'Michael',
      'Millicent',
      'Muriel',
      'Nesta',
      'Nicholas',
      'Nicola(a)',
      'Nigel',
      'Norman',
      'Odo',
      'Oliva',
      'Osbert',
      'Peter',
      'Petronilla',
      'Philip',
      'Philippa',
      'Primeveire',
      'Ralph',
      'Ranulf',
      'Richard',
      'Richenda',
      'Richolda',
      'Robert',
      'Roesia',
      'Roger',
      'Sabelina',
      'Sabina',
      'Saer',
      'Samer',
      'Sarah',
      'Savaric',
      'Silvester',
      'Simon',
      'Stephan',
      'Susanna',
      'Sybil(la)',
      'Terric',
      'Terry',
      'Theobald',
      'Thomas',
      'Thurstan',
      'Umfrey',
      'Waleran',
      'Walter',
      'Warin',
      'William',
      'Wimarc',
      'Wymarc',
      'Ymbert',
    ],
    sur: [
      "Achard",
      "Addinell",
      "Adeney",
      "Aguilon",
      "Albelin",
      "Alevi",
      "Alis",
      "Altard",
      "Ansgot",
      "Anzeray",
      "Arundel",
      "Aschuill",
      "Asselin",
      "Auber",
      "Aubert",
      "Auffrye",
      "Aungier",
      "Auvray",
      "Azor",
      "Bachiler",
      "Baignard",
      "Bailleul",
      "Bainard",
      "Baliol",
      "Ballard",
      "Barkentin",
      "Basnage",
      "Basset",
      "Baudry",
      "Baujot",
      "Bauldry",
      "Bauquemare",
      "Bavent",
      "Beauchamp",
      "Beaumanoir",
      "Beaumarchais",
      "Beaumont",
      "Beauvallet",
      "Becdelièvre",
      "Bele",
      "Belet",
      "Bellecote",
      "Belmis",
      "Benoist",
      "Beringar",
      "Berners",
      "Bernières",
      "Bertran",
      "Bigod",
      "Bigot",
      "Blancbaston",
      "Blangi",
      "Blosbeville",
      "Blouet",
      "Bohon",
      "Bohun",
      "Boisivon",
      "Boislevesque",
      "Boissel",
      "Boivin",
      "Bolam",
      "Bolbec",
      "Boleyn",
      "Bondeville",
      "Bonel",
      "Bonenffant",
      "Boneth",
      "Bonvalet",
      "Bordel",
      "Bosanquet",
      "Bosc",
      "Bosiet",
      "Bossard",
      "Bostel",
      "Boteler",
      "Boterel",
      "Botin",
      "Bouchard",
      "Bourchier",
      "Bourdekin",
      "Bourdet",
      "Bourneville",
      "Bradwardine",
      "Brai",
      "Braund",
      "Brebeuf",
      "Brereton",
      "Bretel",
      "Breteuil",
      "Bretteville",
      "Brimou",
      "Brinon",
      "Briouse",
      "Briqueville",
      "Brix",
      "Brèvedent",
      "Buci",
      "Budi",
      "Bulli",
      "Burci",
      "Burguet",
      "Buron",
      "Bursigni",
      "Busnois",
      "Busquent",
      "Caen",
      "Cailli",
      "Caillot",
      "Cairon",
      "Calmette",
      "Cambrai",
      "Campion",
      "Canaigres",
      "Canouville",
      "Caradas",
      "Carbonnel",
      "Cardon",
      "Cardonell",
      "Carnet",
      "Carteret",
      "Castillon",
      "Caunter",
      "Cavelier",
      "Ceauce",
      "Cecil",
      "Cely",
      "Challenge",
      "Chandos",
      "Chartres",
      "Chauncy",
      "Cheney",
      "Cherbourg",
      "Cioches",
      "Claville",
      "Clerinell",
      "Clinchamps",
      "Coliar",
      "Colleville",
      "Colombelles",
      "Colombieres",
      "Comyn",
      "Conteville",
      "Corbet",
      "Corbière",
      "Corbon",
      "Cormeilles",
      "Corneilles",
      "Corviser",
      "Cosin",
      "Couci",
      "Couer",
      "Courcelle",
      "Courcelles",
      "Courci",
      "Courcon",
      "Courcy",
      "Courseume",
      "Courteney",
      "Craon",
      "Crevecoeur",
      "Croc",
      "Cruel",
      "Cugey",
      "Cul de Louf",
      "Culai",
      "Cumin",
      "Curteys",
      "D'Argouges",
      "D'Auvay",
      "D'Auvrecher",
      "Dacre",
      "Dalyngridge",
      "Damours",
      "Danneville",
      "Danvers",
      "Darcy",
      "Darell",
      "Daunger",
      "De Berchelai",
      "De Felius",
      "De Fry",
      "Deschamps",
      "Desmares",
      "Destain",
      "Devereux",
      "Digby",
      "Ditton",
      "Dive Beugelin",
      "Dol Hugue",
      "Douai",
      "Dreux",
      "Droullin",
      "Druel",
      "Du Buisson",
      "Du Gouey",
      "Du Moucel",
      "Du Perron",
      "Dubosc",
      "Dudley",
      "Dufay",
      "Dufour",
      "Duhamel",
      "Dumont",
      "Dupasquier",
      "Duquesne",
      "Durandal",
      "Durerie",
      "Durjardin",
      "Durville",
      "Duval",
      "Dyel",
      "Ecouland",
      "Elers",
      "Emory",
      "Engerrand",
      "Erquemboure",
      "Espec",
      "Esteney",
      "Evelyn",
      "Eveque",
      "Faceby",
      "Faintree",
      "Fairfax",
      "Falaise",
      "Fantosme",
      "Faucon",
      "Fecamp",
      "Fergant",
      "Ferrers",
      "Ferrieres",
      "Feu",
      "Fiennes",
      "Fitton",
      "Fitzalan",
      "Fitzherbert",
      "Fitzhugh",
      "Fitzroy",
      "Flambard",
      "Folet",
      "Foliot",
      "Fonnereau",
      "Fontemai",
      "Fossard",
      "Fougeres",
      "Fourneaux",
      "Framan",
      "Fresle",
      "Fribois",
      "Froissart",
      "Fromentin",
      "Furnival",
      "Gael",
      "Gand",
      "Garin",
      "Gaveston",
      "Gibard",
      "Giffard",
      "Gillain",
      "Gilpin",
      "Giscard",
      "Glanville",
      "Godart",
      "Godefroy",
      "Gomboult",
      "Gouel",
      "Goulaffre",
      "Gournai",
      "Grai",
      "Grancourt",
      "Grentemesnil",
      "Grenteville",
      "Greslet",
      "Griffin",
      "Grimoult",
      "Grouchet",
      "Groulart",
      "Guernon",
      "Gueron",
      "Guideville",
      "Guiffart",
      "Guildersleeve",
      "Guinand",
      "Gurney",
      "Guyot",
      "Guéribout",
      "Hachet",
      "Halacre",
      "Hallé",
      "Hamage",
      "Harcourt",
      "Haute",
      "Hauville",
      "Hendry",
      "Herbard",
      "Herbert",
      "Heriet",
      "Heuzé",
      "Hewse",
      "Hodenc",
      "Holland",
      "Hotot",
      "Howard",
      "Hue",
      "Hugonin",
      "Hynde",
      "Hédiart",
      "Ide",
      "Jolland",
      "Jubert",
      "L'ile",
      "La Vache",
      "La Verrier",
      "Labbé",
      "Laci",
      "Lallement",
      "Lanquetot",
      "Le Barge",
      "Le Blanc",
      "Le Chandelier",
      "Le Clerc",
      "Le Conte",
      "Le Cordier",
      "Le Cornu",
      "Le Doulcet",
      "Le Goix",
      "Le Grant",
      "Le Gras",
      "Le Jumel",
      "Le Lieur",
      "Le Maistre",
      "Le Marchant",
      "Le Marinier",
      "Le Masson",
      "Le Paulmier",
      "Le Pelletier",
      "Le Pesant",
      "Le Prévost",
      "Le Roux",
      "Le Seigneur",
      "Le Sueur",
      "Le Tellier",
      "Lefebre",
      "Letre",
      "Levasseur",
      "Lhuillier",
      "Libourg",
      "Ligonier",
      "Linesi",
      "Lisieux",
      "Loges",
      "Lorz",
      "Loucelles",
      "Louet",
      "Louvet",
      "Lovell",
      "Lovet",
      "Lucy",
      "Ludel",
      "Lynom",
      "Machault",
      "Machel",
      "Maci",
      "Maignart",
      "Malet",
      "Mallebisse",
      "Malleville",
      "Mallilie",
      "Mallory",
      "Malvallet",
      "Malveisin",
      "Maminot",
      "Mandeville",
      "Manneilli",
      "Mansel",
      "Mantel",
      "Marchmain",
      "Marchés",
      "Marci",
      "Marescot",
      "Margas",
      "Mariage",
      "Marillac",
      "Marisco",
      "Martel",
      "Mathan",
      "Maubenc",
      "Maudit",
      "Mauduit",
      "Maunsell",
      "Maurouard",
      "Mautravers",
      "Maynet",
      "Medley",
      "Mercier",
      "Meri",
      "Merteberge",
      "Mesnage",
      "Meulan",
      "Meules",
      "Meverel",
      "Middleton",
      "Mobec",
      "Moion",
      "Monceaux",
      "Mont-Canisi",
      "Montacute",
      "Montague",
      "Montaigu",
      "Montbrai",
      "Montfiquet",
      "Montfort",
      "Montgomery",
      "Montgommeri",
      "Moron",
      "Morphew",
      "Mortagne",
      "Mortain",
      "Mortemer",
      "Mortimer",
      "Mortmain",
      "Mowbray",
      "Moyaux",
      "Mucedent",
      "Munneville",
      "Murdac",
      "Musard",
      "Musart",
      "Mussegros",
      "Mustel",
      "Nelond",
      "Neot",
      "Nesdin",
      "Neufmarche",
      "Neuville",
      "Neville",
      "Noyers",
      "Omand",
      "Orlebar",
      "Ormond",
      "Osmond",
      "Osmont",
      "Ouistreham",
      "Painel",
      "Paixdecouer",
      "Pancevolt",
      "Pantoul",
      "Papelion",
      "Papon",
      "Paris",
      "Parry",
      "Parthenai",
      "Paschal",
      "Pasquier",
      "Pastforeire",
      "Patris",
      "Paumera",
      "Peccoth",
      "Peche",
      "Peis",
      "Pennant",
      "Perci",
      "Percy",
      "Perroy",
      "Petremol",
      "Peveril",
      "Pevrel",
      "Picard",
      "Picot",
      "Picvini",
      "Pierrepont",
      "Pinel",
      "Pipin",
      "Pippery",
      "Piquiri",
      "Pistres",
      "Pithou",
      "Plucknet",
      "Poer",
      "Poignant",
      "Poillei",
      "Pointel",
      "Pont de l'Arche",
      "Pont",
      "Pontchardon",
      "Port",
      "Postel",
      "Poussin",
      "Prestcote",
      "Puchot",
      "Péricard",
      "Quesnel",
      "Quincarnon",
      "Quincey",
      "Quièvremont",
      "Raimbeaucourt",
      "Rainecourt",
      "Raleigh",
      "Rames",
      "Raoullin",
      "Rassent",
      "Ravenot",
      "Rennes",
      "Renold",
      "Restault",
      "Reviers",
      "Riebou",
      "Rivière",
      "Roard",
      "Rocque",
      "Roger",
      "Romenel",
      "Romé",
      "Ros",
      "Rosai",
      "Rou",
      "Roussel",
      "Runeville",
      "Russell",
      "Sacquerville",
      "Saint-Clair",
      "Saint-Germain",
      "Saint-Helene",
      "Saint-Leger",
      "Saint-Ouen",
      "Saint-Quentin",
      "Saint-Sanson",
      "Saint-Valeri",
      "Saint-Waleri",
      "Sainte-d'Aignaux",
      "Saisset",
      "Sauvigni",
      "Scolland",
      "Senarpont",
      "Senlis",
      "Sept-Meules",
      "Sidney",
      "Simnel",
      "Sollers",
      "Somneri",
      "Sourdeval",
      "Stafford",
      "Stanley",
      "Strivelyn",
      "Stukely",
      "Séguier",
      "Tabraham",
      "Taillebois",
      "Taillepied",
      "Talbot",
      "Talvace",
      "Tessel",
      "Thaon",
      "Theroulde",
      "Thibault",
      "Thiboust",
      "Thorel",
      "Tibon",
      "Tilly",
      "Tinel",
      "Tirel",
      "Toclive",
      "Torteval",
      "Touchet",
      "Tourlaville",
      "Tourmente",
      "Tournai",
      "Tournebulle",
      "Tournebut",
      "Tourneville",
      "Toustain",
      "Tranchant",
      "Trelli",
      "Tulles",
      "Umfraville",
      "Urry",
      "Valance",
      "Valognes",
      "Vane",
      "Vastel",
      "Vatteville",
      "Vaubadon",
      "Vaughan",
      "Vauville",
      "Vaux",
      "Vavassour",
      "Veci",
      "Venois",
      "Ventris",
      "Ver",
      "Verdun",
      "Vernold",
      "Vernon",
      "Verrall",
      "Vesci",
      "Vesli",
      "Veteripont",
      "Vieuxpont",
      "Villehardain",
      "Villon",
      "Vipont",
      "Vis-de-Louf",
      "Vis-de-Loup",
      "Vitalis",
      "Vivers",
      "Viville",
      "Voisin",
      "Wadard",
      "Warci",
      "Watteau",
      "Werables",
      "Willoughby",
      "Wissant",
      "Woodville",
      "Ygou",
      "d'Adreci",
      "d'Aguillon",
      "d'Albert",
      "d'Alencon",
      "d'Amboise",
      "d'Ambray",
      "d'Andeli",
      "d'Andre",
      "d'Angers",
      "d'Angerville",
      "d'Angleville",
      "d'Ansleville",
      "d'Argentan",
      "d'Argues",
      "d'Armentieres",
      "d'Arques",
      "d'Athenous",
      "d'Aubernon",
      "d'Auberville",
      "d'Audrieu",
      "d'Aufai",
      "d'Aumale",
      "d'Aunon",
      "d'Avranches",
      "d'Avre",
      "d'Ecouis",
      "d'Engagne",
      "d'Eresby",
      "d'Escalles",
      "d'Espagne",
      "d'Eu",
      "d'Evreux",
      "d'Helion",
      "d'Hericy",
      "d'Houdetot",
      "d'Incourt",
      "d'Ivri",
      "d'Olgeanc",
      "d'Orbec",
      "d'Orglande",
      "d'Ornontville",
      "d'Ouilli",
      "d'Unepac",
      "de Bailleul",
      "de Balon",
      "de Bans",
      "de Bapaumes",
      "de Barbes",
      "de Beauchamp",
      "de Beaufou",
      "de Beaumais",
      "de Beaumont",
      "de Beauvais",
      "de Bellehache",
      "de Bellemare",
      "de Bellièvre",
      "de Belmeis",
      "de Bercheres",
      "de Bernai",
      "de Bernieres",
      "de Berranger",
      "de Berville",
      "de Bethencourt",
      "de Bienfaite",
      "de Biville",
      "de Blays",
      "de Blundville",
      "de Bouilon",
      "de Bourgueville",
      "de Braose",
      "de Breos",
      "de Burgh",
      "de Cahaihnes",
      "de Calmesnil",
      "de Caulmont",
      "de Caux",
      "de Challon",
      "de Chefderue",
      "de Civille",
      "de Clare",
      "de Corbeil",
      "de Cormeilles",
      "de Coucy",
      "de Courseilles",
      "de Croismare",
      "de Faicterau",
      "de Genville",
      "de Gosbeck",
      "de Grieu",
      "de Hanivel",
      "de Hattes",
      "de Herle",
      "de Ireby",
      "de La Champagne",
      "de La Hay",
      "de La Mare",
      "de La Noue",
      "de La Place",
      "de La Porte",
      "de La Reue",
      "de La Roche",
      "de Lacy",
      "de Lampérière",
      "de Lombelon",
      "de Lorraine",
      "de Malhortye",
      "de Maromme",
      "de Massard",
      "de Mesniel",
      "de Mesnildo",
      "de Monchy",
      "de Monluc",
      "de Montchrestien",
      "de Montfault",
      "de Montfort",
      "de Montgomery",
      "de Moustiers",
      "de Moy",
      "de Munchesney",
      "de Pardieu",
      "de Perronet",
      "de Pinchemont",
      "de Recusson",
      "de Rely",
      "de Reymes",
      "de Roncherolles",
      "de Salynges",
      "de Saussay",
      "de Savage",
      "de Seguzzo",
      "de Servian",
      "de Seyssel",
      "de Tanie",
      "de Tocni",
      "de Toeni",
      "de Valles",
      "de Vandes",
      "de Vaux",
      "de Vesci",
      "de Villy",
      "de Viuepont",
      "de Vymont",
      "de la Pole",
      "des Moutiers",
      "des Vaux",
      "du Bec",
      "du Bois-Hebert",
      "du Bosc-Roard",
      "du Breuil",
      "du Merle",
      "du Perche",
      "du Quesnai",
      "du Saussai",
      "du Theil",
      "du Tilleul",
      "l'Adoube",
      "l'Aigle",
      "l'Ane",
      "l'Appeville",
      "l'Archer",
      "l'Aune",
      "l'Estourmi",
      "la Berviere",
      "la Bruiere",
      "la Cleve",
      "la Foret",
      "la Guierche",
      "la Mare",
      "la Pommeraie",
      "la Riviere",
      "le Berruier",
      "le Blond",
      "le Bouguignon",
      "le Breton",
      "le Despensier",
      "le Flamand",
      "le Gaucher",
      "le Marechal",
      "le Poitevin",
      "le Roux",
      "le Senechal",
      "le Vicomte",
    ],
  }
};
